pipeline:
  identifier: Build_Harness_POC_1683821713869
  name: Build Harness-POC
  orgIdentifier: default
  projectIdentifier: POC
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1683817174712
        repoName: felipetarran/Harness-POC
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      echo <+codebase.commitSha>
                      commithash=<+codebase.commitSha>
                      echo $commithash
                      echo IDTAG=${commithash::5}
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: AWS_REAM
                    region: us-east-1
                    account: "883922500875"
                    imageName: hrnspoc
                    tags:
                      - "1"
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        name: deploy k8s
        identifier: deploy_k8s
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          execution:
            steps:
              - step:
                  type: HelmDeploy
                  name: HelmDeploy_1
                  identifier: HelmDeploy_1
                  spec:
                    skipDryRun: false
                    ignoreReleaseHistFailStatus: false
                  timeout: 10m
            rollbackSteps: []
          service:
            serviceRef: HarnessPoc
          environment:
            environmentRef: HarnessPOC
            deployToAll: false
            infrastructureDefinitions:
              - identifier: kubernetesream
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables: []
        delegateSelectors:
          - helm-delegate
